-- AlterTable
ALTER TABLE `achievements` MODIFY `certificate` VARCHAR(191) NULL,
    MODIFY `dateCreated` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `dateModified` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
